---
- hosts: all
  serial: 1
  any_errors_fatal: true
  gather_facts: true
  sudo: yes

  tasks:
# Randomly run nodetool on a node except on the current node that the upgrade is about to run
    - set_fact:
        nodetool_node: "{{ groups['cassandra'] | difference(inventory_hostname) | random }}"

    - set_fact:
        node_count: "{{ groups['cassandra'] | length }}"

# Print nodetool_node
    - debug:
        msg: "nodetool node is {{ nodetool_node }}"

# Check if any node is down and fail the playbook in next steps later if any node is down
    - name: Check if any node is down
      shell: /opt/app/cassandra/bin/nodetool -h {{ nodetool_node }} -p 7199 status | grep "RAC" | grep -c "UN"
      become_user: cassandra
      register: node_up_count

    - debug:
        msg: "Node UN count {{ node_up_count.stdout }}"

    - debug:
        msg: "Node count from inventory {{ node_count }}"

    - debug:
        msg: "Print only on TRUE condition"
      when: node_up_count.stdout | int == {{ node_count }}

    - debug:
       msg: "Marking playbook failure due to down node on the cluster"
      failed_when: node_up_count.stdout | int != {{ node_count }}
